force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce-CRM/force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order_Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>PREPARING</fullName>
            </value>
            <value>
                <fullName>PAYMENT_PENDING</fullName>
            </value>
            <value>
                <fullName>PAID</fullName>
            </value>
            <value>
                <fullName>CONFIRMED</fullName>
            </value>
            <value>
                <fullName>ASSIGNED</fullName>
            </value>
            <value>
                <fullName>PICKED_UP</fullName>
            </value>
            <value>
                <fullName>OUT_FOR_DELIVERY</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>REFUND_REQUESTED</fullName>
            </value>
            <value>
                <fullName>REFUNDED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OperationsDashboardController.cls
public with sharing class OperationsDashboardController {

    @AuraEnabled(cacheable=true)
    public static Map<String, Integer> getOrderStatusSummary() {

        Map<String, Integer> statusCount =
            new Map<String, Integer>();

        for (AggregateResult ar : [

            SELECT
                Order_Status__c status,
                COUNT(Id) totalCount

            FROM Order__c

            GROUP BY Order_Status__c

        ]) {

            statusCount.put(

                (String) ar.get('status'),

                (Integer) ar.get('totalCount')
            );
        }

        return statusCount;
    }
}